#pragma once

typedef enum {
    PAGE_MAIN_MENU,
    PAGE_EARTH_CITY,
    PAGE_EARTH_TRAINING,
    PAGE_BODY_RESOURCES,
    PAGE_SYSTEM_VIEW,
    PAGE_BODY_VIEW,
    PAGE_SETTINGS,
    PAGE_COUNT
} Page;